### ISSUE TITLE
The module cannot be installed

### ISSUE THREAD

**Issue by invasi0n** [indrivo/drupal_maib_commerce#3]
Hello,

The command "composer require drupal/commerce_maib" returns the following:

`Could not find a matching version of package drupal/commerce_maib. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).`

Thank you!

**Comment by chiril-ungureanu** [comment]
Hi, at the moment there are problems with adding the module on drupal .org. Until we solve the problem you can add the module manually
